quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=mysql123
quarkus.datasource.jdbc.url=jdbc:mysql://mysql-examen:3306/reserva_db

quarkus.http.port=8083
quarkus.http.host=0.0.0.0

libros-api/mp-rest/url=http://ms-valencia-lib-libros:8082

quarkus.fault-tolerance.enabled=true
