quarkus.config.locations=file:/app/central-config/common.properties,file:/app/central-config/ms-valencia-lib-prestamos.properties

quarkus.application.name=ms-valencia-lib-prestamos
quarkus.consul-config.enabled=false
quarkus.http.host=0.0.0.0
