server:
  port: 8030

spring:
  application:
    name: api-gateway

  cloud:

    consul:
      host: consul-examen
      port: 8500
      discovery:
        enabled: true

    gateway:
      routes:

        - id: libros
          uri: lb://ms-valencia-lib-libros
          predicates:
            - Path=/api/libros,/api/libros/**,/api/categorias,/api/categorias/**,/api/autores,/api/autores/**
          filters:
            - StripPrefix=1

        - id: prestamos
          uri: lb://ms-valencia-lib-prestamos
          predicates:
            - Path=/api/prestamos,/api/prestamos/**
          filters:
            - StripPrefix=1

        - id: reservas
          uri: lb://ms-valencia-lib-reserva
          predicates:
            - Path=/api/reservas,/api/reservas/**
          filters:
            - StripPrefix=1
