# Perfil DEV: uso local con Docker Compose.
mysql.host=mysql-examen
mysql.port=3306
mysql.user=root
mysql.password=mysql123
libros.url=http://ms-valencia-lib-libros:8082
gateway.url=http://localhost:8040
